# Generated by Django 5.1.7 on 2025-03-15 14:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_loan', models.PositiveIntegerField(default=0)),
                ('payable_loan', models.PositiveIntegerField(default=0)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_user', to='registration.customersignup')),
            ],
        ),
        migrations.CreateModel(
            name='loanCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_name', models.CharField(max_length=250)),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='loanRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateField(auto_now_add=True)),
                ('status_date', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('reason', models.TextField()),
                ('status', models.CharField(default='pending', max_length=100)),
                ('amount', models.PositiveIntegerField(default=0)),
                ('year', models.PositiveIntegerField(default=1)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='loans.loancategory')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_customer', to='registration.customersignup')),
            ],
        ),
        migrations.CreateModel(
            name='loanTransaction',
            fields=[
                ('transaction', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment', models.PositiveIntegerField(default=0)),
                ('payment_date', models.DateField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_customer', to='registration.customersignup')),
            ],
        ),
        migrations.DeleteModel(
            name='Loan',
        ),
    ]
